-- CREAR TABLAS 
SHOW DATABASES;
USE SWEET_DREAMS;

CREATE TABLE EMPRESA  
(  
EMPRESA_ID INT NOT NULL,  
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCION TEXT(45) NULL,  
RUC INT NOT NULL,  
NOMBRE_COMERCIAL TEXT(45) NOT NULL,  
RAZON_SOCIAL TEXT(10) NOT NULL,  
GENERO TEXT(10) NOT NULL,  
TIPO_CONTRIBUYENTE TEXT(10),  
OFICINA_ID INT NOT NULL, 
ESTADO TEXT(10) NOT NULL 
);   
-- --------------------------------------------------------- 

CREATE TABLE FORMA_PAGO
(  
FORMA_PAGO_ID INT NOT NULL,
TARJETA_INDUSTRIA_ID INT NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCIÓN TEXT(50) NULL, 
ESTADO TEXT(10) NOT NULL,
TIPO_PAGO TEXT(10) NOT NULL
);  


CREATE TABLE PRODUCTO  
(  
PRODUCTO_ID INT NOT NULL,  
TIPO_PRODUCTO_ID INT NOT NULL,  
NOMBRE_PRODUCTO TEXT(45) NOT NULL,  
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCION TEXT(45) NOT NULL,  
ESTADO TEXT(10) NOT NULL
);  
-- ---------------------------------------------------------  

CREATE TABLE CLIENTE  
(  
CLIENTE_ID INT NOT NULL,  
SERVICIO_ID INT NULL,  
FECHA_REGISTO DATETIME NOT NULL,  
DESCRIPCION TEXT(45) NULL,  
CEDULA_RUC INT NOT NULL,  
TELEFONO INT NULL,  
ESTADO TEXT(10) NOT NULL  
);  
-- ---------------------------------------------------------   

CREATE TABLE PAGO
(  
PAGO_ID INT NOT NULL,  
FORMA_PAGO_ID INT NOT NULL,  
DIFERIR_PAGO_ID INT NOT NULL,  
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCIÓN TEXT(50) NULL,  
ESTADO TEXT(10) NOT NULL 
);  
-- --------------------------------------------------------- 

CREATE TABLE TIPO_PRODUCTO
(  
TIPO_PRODUCTO_ID INT NOT NULL,
ORTOPEDICO_ID INT NOT NULL,
MINIMALISTA_ID INT NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
NOMBRE_PRODUCTO TEXT(10) NOT NULL,
DESCRIPCIÓN TEXT(50) NULL, 
ESTADO TEXT(10) NOT NULL
);  
-- --------------------------------------------------------- 

CREATE TABLE FACTURA_CAB
(  
FACTURA_CAB_ID INT NOT NULL,  
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCIÓN TEXT(50) NULL,  
EMPRESA_ID INT NOT NULL,  
OFICINA_ID INT NOT NULL,  
CLIENTE_ID INT NOT NULL,  
ESTADO TEXT(10) NOT NULL  
);  
-- ---------------------------------------------------------   

CREATE TABLE FACTURA_DET
(  
FACTURA_DET_ID INT NOT NULL,  
FACTURA_CAB_ID INT NOT NULL,  
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCIÓN TEXT(50) NULL,  
ESTADO TEXT(10) NOT NULL, 
SERVICIO_ID INT NOT NULL,  
PAGO_ID INT NOT NULL,  
PRECIO_SECTOR_ID INT NOT NULL,  
FORMA_PAGO_ID INT NOT NULL,  
DIFERIR_PAGO_ID INT NOT NULL,  
IVA INT NOT NULL,  
TOTAL_IVA DECIMAL(10,2) NOT NULL,  
DESCUENTO INT NOT NULL,  
TOTAL_FINAL DECIMAL(10,2) NOT NULL 
); 
-- --------------------------------------------------------- 

CREATE TABLE VENTA  
(  
VENTA_ID INT NOT NULL,  
FECHA_REGISTRO DATETIME NOT NULL,  
DESCRIPCION TEXT(45),  
FACTURA_CAB_ID INT NOT NULL,  
PRODUCTO_ID INT NOT NULL,  
CLIENTE_ID INT NOT NULL,  
OFICINA_ID INT NOT NULL,  
TIPO_PRODUCTO_ID INT NOT NULL,  
TIPO_ESTILO_ID INT NOT NULL,  
NIVEL_CONFORT_ID INT NOT NULL,  
PAGO_ID INT NOT NULL,  
SERVICIO_ID INT NOT NULL,  
PRECIO DECIMAL(10,2) NULL,  
ESTADO TEXT(10) NOT NULL 
); 



 