-- AÑADIR CLAVES PRIMARIAS Y FORANEAS 

ALTER TABLE EMPRESA
ADD PRIMARY KEY (EMPRESA_ID);
-- ------------------------------------------------------- 

ALTER TABLE FORMA_PAGO
ADD PRIMARY KEY (FORMA_PAGO_ID),
ADD FOREIGN KEY (TARJETA_INDUSTRIA_ID) REFERENCES TARJETA_INDUSTRIA(TARJETA_INDUSTRIA_ID);
-- ------------------------------------------------------- 

ALTER TABLE PRODUCTO
ADD PRIMARY KEY (PRODUCTO_ID),
ADD FOREIGN KEY (TIPO_PRODUCTO_ID) REFERENCES TIPO_PRODUCTO(TIPO_PRODUCTO_ID);
-- ------------------------------------------------------- 

ALTER TABLE CLIENTE
ADD PRIMARY KEY (CLIENTE_ID),
ADD FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(SERVICIO_ID);
-- ------------------------------------------------------- 

ALTER TABLE PAGO 
ADD PRIMARY KEY (PAGO_ID),
ADD FOREIGN KEY (FORMA_PAGO_ID) REFERENCES FORMA_PAGO (FORMA_PAGO_ID),
ADD FOREIGN KEY (DIFERIR_PAGO_ID) REFERENCES DIFERIR_PAGO (DIFERIR_PAGO_ID); 
-- ------------------------------------------------------- 

ALTER TABLE TIPO_PRODUCTO
ADD PRIMARY KEY (TIPO_PRODUCTO_ID),
ADD FOREIGN KEY (ORTOPEDICO_ID) REFERENCES ORTOPEDICO(ORTOPEDICO_ID),
ADD FOREIGN KEY (MINIMALISTA_ID) REFERENCES MINIMALISTA(MINIMALISTA_ID);
-- ------------------------------------------------------- 

ALTER TABLE FACTURA_CAB 
ADD PRIMARY KEY (FACTURA_CAB_ID); 
-- ------------------------------------------------------- 

ALTER TABLE FACTURA_DET 
ADD PRIMARY KEY (FACTURA_DET_ID),
ADD FOREIGN KEY (FACTURA_CAB_ID) REFERENCES FACTURA_CAB (FACTURA_CAB_ID),
ADD FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO (SERVICIO_ID),
ADD FOREIGN KEY (PAGO_ID) REFERENCES PAGO (PAGO_ID), 
ADD FOREIGN KEY (PRECIO_SECTOR_ID) REFERENCES PRECIO_SECTOR (PRECIO_SECTOR_ID),
ADD FOREIGN KEY (FORMA_PAGO_ID) REFERENCES FORMA_PAGO (FORMA_PAGO_ID),
ADD FOREIGN KEY (DIFERIR_PAGO_ID) REFERENCES DIFERIR_PAGO (DIFERIR_PAGO_ID); 
-- ------------------------------------------------------- 

ALTER TABLE VENTA
ADD PRIMARY KEY (VENTA_ID),
ADD FOREIGN KEY (FACTURA_CAB_ID) REFERENCES FACTURA_CAB(FACTURA_CAB_ID),
ADD FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID),
ADD FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID),
ADD FOREIGN KEY (OFICINA_ID) REFERENCES OFICINA(OFICINA_ID),
ADD FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID),
ADD FOREIGN KEY (TIPO_PRODUCTO_ID) REFERENCES TIPO_PRODUCTO(TIPO_PRODUCTO_ID),
ADD FOREIGN KEY (TIPO_ESTILO_ID) REFERENCES TIPO_ESTILO(TIPO_ESTILO_ID),
ADD FOREIGN KEY (NIVEL_CONFORT_ID) REFERENCES NIVEL_CONFORT(NIVEL_CONFORT_ID),
ADD FOREIGN KEY (PAGO_ID) REFERENCES PAGO(PAGO_ID),
ADD FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(SERVICIO_ID);
